<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net472</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
		<AssemblyName>Asher.Launcher</AssemblyName>
		<RootNamespace>Asher.Launcher</RootNamespace>
		<Platforms>AnyCPU;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Asher.Runtime\Asher.Runtime.csproj" />
	</ItemGroup>

</Project>

