<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>AnyCPU;x86</Platforms>
    <AssemblyName>Asher.Host</AssemblyName>
    <RootNamespace>Asher.Host</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Asher.Core\Asher.Core.csproj" />
    <ProjectReference Include="..\Asher.Services\Asher.Services.csproj" />
  </ItemGroup>

  <Import Project="InstallPayload.targets" />

</Project>
